version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=polieatsadmin
      - POSTGRESQL_PASSWORD=polieatsapp
      - POSTGRESQL_DATABASE=main_polieats_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local