name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Check GitHub Token Permissions'
      run: gh auth status

    - name: 'Auto-assign issue or pull request'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: gbrasil720
          numOfAssignee: 1
      continue-on-error: true # Allow the workflow to proceed even if this step fails.

    - name: 'Add reviewer to pull requests'
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const pull_number = context.payload.pull_request.number;
          const author = context.payload.pull_request.user.login;

          const reviewer = 'gbrasil720';
          if (author !== reviewer) {
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers: [reviewer]
            });
            console.log(`Reviewer ${reviewer} successfully requested.`);
          } else {
            console.log('Cannot request review from the pull request author.');
          }
